services:
  # Serviço 1: Banco de Dados PostgreSQL
  - type: pserv
    name: locker-db-postgres
    plan: free
    postgres:
      version: "15"

  # Serviço 2: Aplicação Spring Boot (Web Service)
  - type: web
    name: locker-service-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:

      # 1. Construímos a URL JDBC manualmente usando a interpolação de serviços do Render.
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${locker-db-postgres.host}:${locker-db-postgres.port}/${locker-db-postgres.database}

      # 2. Mapeamos o usuário do banco de dados do Render.
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: locker-db-postgres
          property: user

      # 3. Mapeamos a senha do banco de dados do Render.
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: locker-db-postgres
          property: password

      # 4. (Opcional, mas boa prática) Definimos explicitamente o driver.
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver

      # 5. Mantemos o perfil de produção.
      - key: SPRING_PROFILES_ACTIVE
        value: production