services:
  # Serviço 1: Banco de Dados PostgreSQL
  - type: pserv
    name: locker-db-postgres
    # A linha 'runtime: postgres' foi REMOVIDA daqui
    plan: free
    postgres:
      version: "15"

  # Serviço 2: Aplicação Spring Boot (Web Service)
  - type: web
    name: locker-service-api
    runtime: docker # 'runtime' é usado aqui, para o serviço web
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        fromDatabase:
          name: locker-db-postgres
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: locker-db-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: locker-db-postgres
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: production