services:
  # Serviço 1: Banco de Dados PostgreSQL
  - type: pserv
    name: locker-db-postgres
    plan: free
    postgres:
      version: "15"

  # Serviço 2: Aplicação Spring Boot (Web Service)
  - type: web
    name: locker-service-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      # --- CORREÇÃO FINAL ---
      # Usando as variáveis padrão do Spring e a connection string interna do Render

      # O Render fornece uma URL de conexão interna já compatível com JDBC.
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: locker-db-postgres
          property: internalConnectionString

      # Mapeamos o usuário do banco de dados do Render.
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: locker-db-postgres
          property: user

      # Mapeamos a senha do banco de dados do Render.
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: locker-db-postgres
          property: password

      # (Opcional, mas boa prática) Definimos explicitamente o driver.
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver