services:
  # Serviço 1: Banco de Dados PostgreSQL
  - type: pserv
    name: locker-db-postgres
    runtime: postgres
    plan: free # Usa o plano gratuito do Render
    postgres:
      version: "15"

  # Serviço 2: Aplicação Spring Boot (Web Service)
  - type: web
    name: locker-service-api
    runtime: docker
    plan: free # Usa o plano gratuito do Render
    dockerfilePath: ./Dockerfile
    envVars:
      # Render injeta a URL do banco de dados automaticamente
      - key: DB_URL
        fromDatabase:
          name: locker-db-postgres # Nome do serviço de banco de dados definido acima
          property: connectionString
      # As outras credenciais também são injetadas
      - key: DB_USERNAME
        fromDatabase:
          name: locker-db-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: locker-db-postgres
          property: password
      # Garante que a aplicação use o perfil 'production' do Spring se necessário
      - key: SPRING_PROFILES_ACTIVE
        value: production